credentials:
  usernames:
    admin:
      login: 3apP_AdmiN514_!
      name: Admin
      password: $2b$12$S8GV46fCFS0hoEG27U7Jb.WOnDU3agCyam2U7CB42ePeTeteA2/eW
    user:
      login: 3apP_UseR017_!
      name: User
      password: $2b$12$pQlt3c.pGPCe3jgXuCN5SeBOD6By7m1ys/nTGTU9SrbaB91iPiMLO
    user2:
      login: 3apP_UseR018_!
      name: User2
      password: $2b$12$LpR.f90l5qirA6Y90jS28OwH2v/yU4vCbWbxFrTspdZ3Fpv6wo.bu
cookie:
  expiry_days: 30
  key: 6FDAF537F91BF
  name: app_login_cookies